
// Autogenerated by geninfo, do not edit

package gcewing.prospecting;

public class Info {

    static final String modName = "ProspectingCraft";
    static final String modID = "prospectingcraft";
    static final String versionNumber = "1.2.2";
    static final String versionBounds = "[1.2,1.3)";
    static final String acceptedMinecraftVersions = "1.7.10";

}
